"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Bell, Check, Clock3, Globe2, Headphones, Languages, Pause, Play, Plus, Radio, Settings2, Sparkles, Square, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

type Station = { id:string; name:string; city:string; country:string; flag:string; language:string; active:boolean; topic:string; summary:string; relevance:number; updated:string; color:string };
const defaults: Station[] = [
  {id:"formula",name:"Radio Fórmula",city:"Ciudad de México",country:"México",flag:"🇲🇽",language:"Español",active:true,topic:"Economía y tecnología en México",summary:"Analizan la inversión en centros de datos y el crecimiento de la infraestructura de inteligencia artificial en México.",relevance:96,updated:"hace 8 s",color:"coral"},
  {id:"w-radio",name:"W Radio",city:"Ciudad de México",country:"México",flag:"🇲🇽",language:"Español",active:true,topic:"Noticias nacionales",summary:"Conversan sobre política económica, nearshoring y nuevas inversiones industriales anunciadas para el norte del país.",relevance:87,updated:"hace 16 s",color:"amber"},
  {id:"bbc",name:"BBC World Service",city:"Londres",country:"Reino Unido",flag:"🇬🇧",language:"Inglés",active:true,topic:"Robótica e inteligencia artificial",summary:"Entrevistan a investigadores sobre robots humanoides, seguridad y el impacto de modelos fundacionales en la industria.",relevance:93,updated:"hace 11 s",color:"blue"},
  {id:"france-info",name:"France Info",city:"París",country:"Francia",flag:"🇫🇷",language:"Francés",active:true,topic:"Regulación europea de IA",summary:"Explican nuevas obligaciones para desarrolladores de modelos fundacionales y comparan Europa con Estados Unidos.",relevance:91,updated:"hace 12 s",color:"violet"},
  {id:"npr",name:"NPR",city:"Washington, D.C.",country:"Estados Unidos",flag:"🇺🇸",language:"Inglés",active:true,topic:"Ciencia y educación",summary:"Un reportaje revisa cómo las universidades incorporan agentes de IA en investigación, docencia y aprendizaje.",relevance:82,updated:"hace 24 s",color:"teal"},
];

export default function Home() {
  const [stations,setStations]=useState(defaults), [running,setRunning]=useState(false), [listening,setListening]=useState<string|null>(null), [elapsed,setElapsed]=useState(0), [manage,setManage]=useState(false), [open,setOpen]=useState(false), [language,setLanguage]=useState("es");
  const [newStation,setNewStation]=useState({name:"",city:"",country:"",url:""});
  useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setElapsed(v=>v+1),1000);return()=>window.clearInterval(timer)},[running]);
  const active=useMemo(()=>stations.filter(s=>s.active).sort((a,b)=>b.relevance-a.relevance),[stations]);
  const playing=stations.find(s=>s.id===listening);
  const duration=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`;
  const stopStart=()=>{if(running){setRunning(false);setListening(null);setElapsed(0)}else setRunning(true)};
  const add=()=>{if(!newStation.name.trim())return;setStations(s=>[...s,{id:`new-${Date.now()}`,name:newStation.name,city:newStation.city||"Sin ciudad",country:newStation.country||"Otro país",flag:"🌐",language:"Por detectar",active:true,topic:"Esperando análisis",summary:"El resumen aparecerá al iniciar la sesión.",relevance:0,updated:"sin analizar",color:"blue"}]);setNewStation({name:"",city:"",country:"",url:""});setOpen(false)};

  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b bg-background/95"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3 px-5 py-4 lg:px-8">
      <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Radio className="size-5"/></div><div><h1 className="text-lg font-semibold sm:text-xl">MySelectiveRadioGarden</h1><p className="hidden text-sm text-muted-foreground sm:block">Tu radar mundial de conversaciones</p></div></div>
      <div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setManage(v=>!v)}><Settings2 className="size-4"/><span className="hidden sm:inline">Estaciones</span></Button><Button onClick={stopStart} className={running?"bg-rose-600 text-white hover:bg-rose-700":""}>{running?<Square className="size-4 fill-current"/>:<Play className="size-4 fill-current"/>}{running?"Detener":"Empezar análisis"}</Button></div>
    </div></header>

    <div className="mx-auto max-w-[1500px] px-5 py-5 lg:px-8 lg:py-7">
      <section className="mb-6 grid gap-4 xl:grid-cols-[1fr_auto]"><div className={`session ${running?"session-on":""}`}><div className="flex min-w-0 items-start gap-4"><div className={`flex size-11 shrink-0 items-center justify-center rounded-full ${running?"bg-emerald-500/15 text-emerald-700":"bg-muted text-muted-foreground"}`}>{running?<Activity className="size-5"/>:<Pause className="size-5"/>}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{running?"Análisis en curso":"Listo para explorar el mundo"}</h2>{running&&<Badge className="bg-emerald-600 text-white">EN VIVO</Badge>}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{running?`${active.length} estaciones activas · Resúmenes cada 30 segundos`:`El Spark sólo trabajará durante la sesión que tú inicies.`}</p></div></div>{running&&<div className="text-right text-sm"><p className="text-muted-foreground">Duración</p><p className="font-mono font-semibold">{duration}</p></div>}</div>
      <div className="flex items-center gap-3 rounded-2xl border bg-card px-4 py-3"><Languages className="size-4 text-muted-foreground"/><Label>Resúmenes en</Label><Select value={language} onValueChange={setLanguage}><SelectTrigger className="w-[130px] border-0 bg-muted"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="es">Español</SelectItem><SelectItem value="en">English</SelectItem><SelectItem value="fr">Français</SelectItem><SelectItem value="it">Italiano</SelectItem><SelectItem value="zh">中文</SelectItem><SelectItem value="ja">日本語</SelectItem><SelectItem value="ko">한국어</SelectItem><SelectItem value="he">עברית</SelectItem><SelectItem value="ar">العربية</SelectItem></SelectContent></Select></div></section>

      {manage&&<section className="mb-6 rounded-3xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-semibold">Estaciones de esta sesión</h2><p className="mt-1 text-sm text-muted-foreground">Activa sólo las transmisiones que quieras analizar.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button size="sm"/>}><Plus className="size-4"/>Agregar estación</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Agregar estación</DialogTitle><DialogDescription>Registra una estación y su enlace oficial o de Radio Garden.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><Field id="name" label="Nombre" value={newStation.name} set={v=>setNewStation({...newStation,name:v})}/><div className="grid grid-cols-2 gap-3"><Field id="city" label="Ciudad" value={newStation.city} set={v=>setNewStation({...newStation,city:v})}/><Field id="country" label="País" value={newStation.country} set={v=>setNewStation({...newStation,country:v})}/></div><Field id="url" label="URL oficial o Radio Garden" value={newStation.url} set={v=>setNewStation({...newStation,url:v})}/></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={add} disabled={!newStation.name.trim()}>Agregar</Button></DialogFooter></DialogContent></Dialog></div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{stations.map(s=><div key={s.id} className="flex items-center gap-3 rounded-2xl bg-muted/70 p-3"><Checkbox checked={s.active} onCheckedChange={c=>setStations(all=>all.map(x=>x.id===s.id?{...x,active:c===true}:x))}/><span className="text-xl">{s.flag}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{s.name}</p><p className="truncate text-xs text-muted-foreground">{s.city} · {s.language}</p></div><Button variant="ghost" size="icon-sm" onClick={()=>setStations(all=>all.filter(x=>x.id!==s.id))}><Trash2 className="size-4"/></Button></div>)}</div></section>}

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><section><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles className="size-5"/><h2 className="text-xl font-semibold">Conversaciones ahora</h2></div><p className="mt-1 text-sm text-muted-foreground">Ordenadas por relevancia para tus intereses</p></div><p className="text-sm text-muted-foreground">{active.length} estaciones seleccionadas</p></div><div className="grid gap-4 md:grid-cols-2">{active.map((s,i)=><StationCard key={s.id} station={s} rank={i+1} running={running} selected={listening===s.id} onListen={()=>setListening(listening===s.id?null:s.id)}/>)}</div></section>
      <aside className="space-y-5"><section className="rounded-3xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Headphones className="size-5"/><h2 className="font-semibold">Reproductor</h2></div>{playing?<><div className="now-playing"><span>{playing.flag}</span><div className="bars"><i/><i/><i/><i/><i/></div></div><p className="mt-4 font-semibold">{playing.name}</p><p className="mt-1 text-sm text-muted-foreground">{playing.city} · En vivo</p><Button className="mt-4 w-full" onClick={()=>setListening(null)}><Pause className="size-4 fill-current"/>Pausar</Button><p className="mt-3 text-center text-xs text-muted-foreground">Las demás estaciones continúan bajo análisis.</p></>:<div className="rounded-2xl bg-muted/70 px-4 py-8 text-center"><Radio className="mx-auto size-8 text-muted-foreground"/><p className="mt-3 text-sm font-medium">Ninguna estación seleccionada</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Comienza el análisis y elige la conversación más interesante.</p></div>}</section>
      <section className="rounded-3xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Bell className="size-5"/><h2 className="font-semibold">Tus intereses</h2></div><div className="flex flex-wrap gap-2">{["Inteligencia artificial","NVIDIA","Robótica","México","Semiconductores"].map(t=><Badge key={t} variant="secondary" className="rounded-full px-3 py-1.5 font-normal">{t}</Badge>)}</div><div className="mt-5 flex items-center justify-between border-t pt-4"><div><p className="text-sm font-medium">Alertas relevantes</p><p className="text-xs text-muted-foreground">Sólo 85% o más</p></div><Switch defaultChecked/></div></section>
      <section className="rounded-3xl bg-primary p-5 text-primary-foreground"><div className="flex items-center gap-2"><Globe2 className="size-5"/><h2 className="font-semibold">Spark conectado</h2></div><div className="mt-4 space-y-3 text-sm text-primary-foreground/75"><Status name="API local" value="Lista"/><Status name="Cloudflare Tunnel" value="Seguro"/><div className="flex justify-between"><span>Modelo ASR</span><span className="text-primary-foreground">Parakeet</span></div></div></section></aside></div>
    </div>
  </main>
}

function Field({id,label,value,set}:{id:string;label:string;value:string;set:(v:string)=>void}){return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={e=>set(e.target.value)}/></div>}
function Status({name,value}:{name:string;value:string}){return <div className="flex justify-between"><span>{name}</span><span className="flex items-center gap-1 text-primary-foreground"><Check className="size-3.5"/>{value}</span></div>}
function StationCard({station:s,rank,running,selected,onListen}:{station:Station;rank:number;running:boolean;selected:boolean;onListen:()=>void}){return <article className={`station-card station-${s.color} ${selected?"station-selected":""}`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="station-rank">{rank}</div><div className="min-w-0"><div className="flex items-center gap-2"><span className="text-xl">{s.flag}</span><h3 className="truncate font-semibold">{s.name}</h3></div><p className="truncate text-sm text-muted-foreground">{s.city} · {s.language}</p></div></div><div className="score" style={{"--score":`${s.relevance*3.6}deg`} as React.CSSProperties}><span>{running?s.relevance:"—"}</span></div></div><div className="mt-5"><p className="mb-1 text-xs font-semibold uppercase tracking-widest text-muted-foreground">Tema actual</p><h4 className="text-lg font-semibold">{running?s.topic:"Esperando una nueva sesión"}</h4><p className="mt-3 min-h-[4.5rem] text-[15px] leading-6 text-foreground/75">{running?s.summary:"Presiona Empezar análisis para comparar lo que ocurre en esta estación."}</p></div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3.5"/>{running?s.updated:"En espera"}</span><Button disabled={!running} size="sm" variant={selected?"default":"outline"} onClick={onListen}>{selected?<Pause className="size-4"/>:<Headphones className="size-4"/>}{selected?"Escuchando":"Escuchar"}</Button></div></article>}
